### ISSUE TITLE
There is little to no documentation inside of any of the rust files

### ISSUE THREAD

**Issue by bevinart** [BlidDev/Glang#2]
As the title says, there is little to no documentation in any of the src/*.rs files. I also feel that there is a major organization issue when looking more through the code, such as in src/main.rs. I've made a fork of the repository and will try to go through and document as much as I can

**Comment by BlidDev** [comment]
Hi, there's indeed a lack of comments in the souce files, I planned to add comments to the code anyway before making my next video about it but your changes are more than welcome. I also plan to rearrage some stuff in general like splitting the code into smaller and clearer files. But thanks for the help :)
